2021-04-03 19:44:19,056 INFO: eastbourne startup [in /hdd/code/eastbournecottage/app/__init__.py:29]
2021-04-03 19:44:19,120 INFO: eastbourne startup [in /hdd/code/eastbournecottage/app/__init__.py:29]
2021-04-03 19:44:19,139 INFO: eastbourne startup [in /hdd/code/eastbournecottage/app/__init__.py:29]
2021-04-03 19:44:19,231 INFO: eastbourne startup [in /hdd/code/eastbournecottage/app/__init__.py:29]
2021-04-03 19:45:16,444 INFO: eastbourne startup [in /hdd/code/eastbournecottage/app/__init__.py:29]
2021-04-03 19:45:16,530 INFO: eastbourne startup [in /hdd/code/eastbournecottage/app/__init__.py:29]
2021-04-03 19:45:16,590 INFO: eastbourne startup [in /hdd/code/eastbournecottage/app/__init__.py:29]
2021-04-03 19:45:16,597 INFO: eastbourne startup [in /hdd/code/eastbournecottage/app/__init__.py:29]
2021-04-03 20:03:45,839 INFO: eastbourne startup [in /hdd/code/eastbournecottage/app/__init__.py:29]
2021-04-03 20:03:45,899 INFO: eastbourne startup [in /hdd/code/eastbournecottage/app/__init__.py:29]
2021-04-03 20:03:45,943 INFO: eastbourne startup [in /hdd/code/eastbournecottage/app/__init__.py:29]
2021-04-03 20:03:45,997 INFO: eastbourne startup [in /hdd/code/eastbournecottage/app/__init__.py:29]
2021-04-03 20:04:00,649 ERROR: Exception on /set_billing_settings [POST] [in /hdd/code/eastbournecottage/venv/lib/python3.8/site-packages/flask/app.py:1891]
Traceback (most recent call last):
  File "/hdd/code/eastbournecottage/venv/lib/python3.8/site-packages/flask/app.py", line 2447, in wsgi_app
    response = self.full_dispatch_request()
  File "/hdd/code/eastbournecottage/venv/lib/python3.8/site-packages/flask/app.py", line 1952, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/hdd/code/eastbournecottage/venv/lib/python3.8/site-packages/flask/app.py", line 1821, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/hdd/code/eastbournecottage/venv/lib/python3.8/site-packages/flask/_compat.py", line 39, in reraise
    raise value
  File "/hdd/code/eastbournecottage/venv/lib/python3.8/site-packages/flask/app.py", line 1950, in full_dispatch_request
    rv = self.dispatch_request()
  File "/hdd/code/eastbournecottage/venv/lib/python3.8/site-packages/flask/app.py", line 1936, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/hdd/code/eastbournecottage/venv/lib/python3.8/site-packages/flask_login/utils.py", line 272, in decorated_view
    return func(*args, **kwargs)
  File "/hdd/code/eastbournecottage/app/routes.py", line 628, in set_billing_settings
    if sum(filter(lambda row: row['amountDue'], filter(lambda row: not row['deleteFlag'], json_payment_breakpoints))) == 100:
TypeError: unsupported operand type(s) for +: 'int' and 'dict'
2021-04-03 20:08:23,328 INFO: eastbourne startup [in /hdd/code/eastbournecottage/app/__init__.py:29]
2021-04-03 20:25:42,005 INFO: eastbourne startup [in /hdd/code/eastbournecottage/app/__init__.py:29]
2021-04-03 20:25:42,096 INFO: eastbourne startup [in /hdd/code/eastbournecottage/app/__init__.py:29]
2021-04-03 20:25:42,119 INFO: eastbourne startup [in /hdd/code/eastbournecottage/app/__init__.py:29]
2021-04-03 20:25:42,213 INFO: eastbourne startup [in /hdd/code/eastbournecottage/app/__init__.py:29]
2021-04-03 20:26:57,922 INFO: eastbourne startup [in /hdd/code/eastbournecottage/app/__init__.py:29]
2021-04-03 20:26:57,991 INFO: eastbourne startup [in /hdd/code/eastbournecottage/app/__init__.py:29]
2021-04-03 20:26:58,064 INFO: eastbourne startup [in /hdd/code/eastbournecottage/app/__init__.py:29]
2021-04-03 20:26:58,111 INFO: eastbourne startup [in /hdd/code/eastbournecottage/app/__init__.py:29]
2021-04-03 20:27:40,207 INFO: eastbourne startup [in /hdd/code/eastbournecottage/app/__init__.py:29]
2021-04-03 20:27:40,257 INFO: eastbourne startup [in /hdd/code/eastbournecottage/app/__init__.py:29]
2021-04-03 20:27:40,287 INFO: eastbourne startup [in /hdd/code/eastbournecottage/app/__init__.py:29]
2021-04-03 20:27:40,367 INFO: eastbourne startup [in /hdd/code/eastbournecottage/app/__init__.py:29]
2021-04-03 20:33:13,719 INFO: eastbourne startup [in /hdd/code/eastbournecottage/app/__init__.py:29]
2021-04-03 20:33:13,753 INFO: eastbourne startup [in /hdd/code/eastbournecottage/app/__init__.py:29]
2021-04-03 20:33:13,822 INFO: eastbourne startup [in /hdd/code/eastbournecottage/app/__init__.py:29]
2021-04-03 20:33:13,901 INFO: eastbourne startup [in /hdd/code/eastbournecottage/app/__init__.py:29]
2021-04-03 20:33:21,134 ERROR: Exception on /set_billing_settings [POST] [in /hdd/code/eastbournecottage/venv/lib/python3.8/site-packages/flask/app.py:1891]
Traceback (most recent call last):
  File "/hdd/code/eastbournecottage/venv/lib/python3.8/site-packages/flask/app.py", line 2447, in wsgi_app
    response = self.full_dispatch_request()
  File "/hdd/code/eastbournecottage/venv/lib/python3.8/site-packages/flask/app.py", line 1953, in full_dispatch_request
    return self.finalize_request(rv)
  File "/hdd/code/eastbournecottage/venv/lib/python3.8/site-packages/flask/app.py", line 1968, in finalize_request
    response = self.make_response(rv)
  File "/hdd/code/eastbournecottage/venv/lib/python3.8/site-packages/flask/app.py", line 2097, in make_response
    raise TypeError(
TypeError: The view function did not return a valid response. The function either returned None or ended without a return statement.
2021-04-03 20:34:02,689 INFO: eastbourne startup [in /hdd/code/eastbournecottage/app/__init__.py:29]
2021-04-03 20:34:02,772 INFO: eastbourne startup [in /hdd/code/eastbournecottage/app/__init__.py:29]
2021-04-03 20:34:02,775 INFO: eastbourne startup [in /hdd/code/eastbournecottage/app/__init__.py:29]
2021-04-03 20:34:02,789 INFO: eastbourne startup [in /hdd/code/eastbournecottage/app/__init__.py:29]
2021-04-03 20:39:43,213 INFO: eastbourne startup [in /hdd/code/eastbournecottage/app/__init__.py:29]
2021-04-03 20:39:43,302 INFO: eastbourne startup [in /hdd/code/eastbournecottage/app/__init__.py:29]
2021-04-03 20:39:43,402 INFO: eastbourne startup [in /hdd/code/eastbournecottage/app/__init__.py:29]
2021-04-03 20:39:43,408 INFO: eastbourne startup [in /hdd/code/eastbournecottage/app/__init__.py:29]
2021-04-03 21:08:20,362 INFO: eastbourne startup [in /hdd/code/eastbournecottage/app/__init__.py:29]
2021-04-03 21:08:20,430 INFO: eastbourne startup [in /hdd/code/eastbournecottage/app/__init__.py:29]
2021-04-03 21:08:20,506 INFO: eastbourne startup [in /hdd/code/eastbournecottage/app/__init__.py:29]
2021-04-03 21:08:20,598 INFO: eastbourne startup [in /hdd/code/eastbournecottage/app/__init__.py:29]
2021-04-03 21:08:44,167 ERROR: Exception on /set_billing_settings [POST] [in /hdd/code/eastbournecottage/venv/lib/python3.8/site-packages/flask/app.py:1891]
Traceback (most recent call last):
  File "/hdd/code/eastbournecottage/venv/lib/python3.8/site-packages/flask/app.py", line 2447, in wsgi_app
    response = self.full_dispatch_request()
  File "/hdd/code/eastbournecottage/venv/lib/python3.8/site-packages/flask/app.py", line 1952, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/hdd/code/eastbournecottage/venv/lib/python3.8/site-packages/flask/app.py", line 1821, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/hdd/code/eastbournecottage/venv/lib/python3.8/site-packages/flask/_compat.py", line 39, in reraise
    raise value
  File "/hdd/code/eastbournecottage/venv/lib/python3.8/site-packages/flask/app.py", line 1950, in full_dispatch_request
    rv = self.dispatch_request()
  File "/hdd/code/eastbournecottage/venv/lib/python3.8/site-packages/flask/app.py", line 1936, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/hdd/code/eastbournecottage/venv/lib/python3.8/site-packages/flask_login/utils.py", line 272, in decorated_view
    return func(*args, **kwargs)
  File "/hdd/code/eastbournecottage/app/routes.py", line 646, in set_billing_settings
    if row['amountDue'] <= 0 or row['dueBy'] <= 0:
TypeError: '<=' not supported between instances of 'str' and 'int'
2021-04-03 21:12:04,614 INFO: eastbourne startup [in /hdd/code/eastbournecottage/app/__init__.py:29]
2021-04-03 21:12:04,641 INFO: eastbourne startup [in /hdd/code/eastbournecottage/app/__init__.py:29]
2021-04-03 21:12:04,663 INFO: eastbourne startup [in /hdd/code/eastbournecottage/app/__init__.py:29]
2021-04-03 21:12:04,687 INFO: eastbourne startup [in /hdd/code/eastbournecottage/app/__init__.py:29]
2021-04-03 21:12:21,983 ERROR: Exception on /set_billing_settings [POST] [in /hdd/code/eastbournecottage/venv/lib/python3.8/site-packages/flask/app.py:1891]
Traceback (most recent call last):
  File "/hdd/code/eastbournecottage/venv/lib/python3.8/site-packages/flask/app.py", line 2447, in wsgi_app
    response = self.full_dispatch_request()
  File "/hdd/code/eastbournecottage/venv/lib/python3.8/site-packages/flask/app.py", line 1952, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/hdd/code/eastbournecottage/venv/lib/python3.8/site-packages/flask/app.py", line 1821, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/hdd/code/eastbournecottage/venv/lib/python3.8/site-packages/flask/_compat.py", line 39, in reraise
    raise value
  File "/hdd/code/eastbournecottage/venv/lib/python3.8/site-packages/flask/app.py", line 1950, in full_dispatch_request
    rv = self.dispatch_request()
  File "/hdd/code/eastbournecottage/venv/lib/python3.8/site-packages/flask/app.py", line 1936, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/hdd/code/eastbournecottage/venv/lib/python3.8/site-packages/flask_login/utils.py", line 272, in decorated_view
    return func(*args, **kwargs)
  File "/hdd/code/eastbournecottage/app/routes.py", line 646, in set_billing_settings
    if int(row['amountDue']) <= 0 or int(row['dueBy']) <= 0:
TypeError: int() argument must be a string, a bytes-like object or a number, not 'NoneType'
2021-04-03 21:20:56,734 INFO: eastbourne startup [in /hdd/code/eastbournecottage/app/__init__.py:29]
2021-04-03 21:20:56,739 INFO: eastbourne startup [in /hdd/code/eastbournecottage/app/__init__.py:29]
